version: '3.8'

services:
    nginx:
        container_name: nginx
        image: nginx:alpine
        ports:
            - "8000:80"
        depends_on:
            - app
            - db
        volumes:
            - ./src:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d
    
    db:
        image: postgres
        container_name: pgsql
        ports:
            - "5432:5432"
        volumes:
            - ./pgsql/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=haka
            - POSTGRES_PASSWORD=postgres
    app:
        container_name: hakaton_backend
        build: 
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www
